...

diff --git a/latest b/latest
--- a/latest
+++ b/latest
@@ -3,11 +3,82 @@
 # author:       Li Junhao           l@x-cmd.com
 # license:      GPLv3
 
+# Section: main
+
 # jump to a folder contains: jc bin
 # jump to a child folder: jc lib
 # jump to a father folder: jo opening; cd .
 
 # cd /u/l/
+
+___x_cmd_cd(){
+    local p="$1"
+
+    if [ -d "$p" ]; then
+        ___x_cmd_cd_origin "$p"
+        return
+    fi
+
+    case "$p" in
+        "")      ___x_cmd_cd_origin              ;;
+        ...)     ___x_cmd_cd_origin ../..        ;;
+        ....)    ___x_cmd_cd_origin ../../../    ;;
+        ../*)    ___x_cmd_cd_back "${p#../}"     ;;
+        ./*)     ___x_cmd_cd_choose "$(find . -name "*${p#./}*" -type d 2>/dev/null)" ;;
+
+        # Self defined documents
+        -%)
+            ___X_CMD_CD_HISTORY="$(printf "%s" "$___X_CMD_CD_HISTORY" | awk "$___X_CMD_AWK_CODE")"
+            printf "%s\n" "$___X_CMD_CD_HISTORY"
+            ;;
+        -/)
+            # very less used
+            ___X_CMD_CD_HISTORY=
+            ;;
+        -)
+            # cd to most recent
+            ___x_cmd_cd_origin -
+            ;;
+        --)
+            ___X_CMD_CD_HISTORY="$(printf "%s" "$___X_CMD_CD_HISTORY" | awk "$___X_CMD_AWK_CODE")"
+            local target="${___X_CMD_CD_HISTORY#*
+*
+}"
+            [ "$target" = "$___X_CMD_CD_HISTORY" ] && printf "%s\n" "cd: no such directory: " >&2 && return
+            target="${target%%
+*}"
+            ___x_cmd_cd_origin "$target"
+            ;;
+        -*)
+            ___X_CMD_CD_HISTORY="$(printf "%s" "$___X_CMD_CD_HISTORY" | awk "$___X_CMD_AWK_CODE")"
+            ___x_cmd_cd_origin "$(awk "FNR <= 1" <<A
+$(printf "%s" "$___X_CMD_CD_HISTORY" | grep "${p#-}")
+A
+)"
+            ;;
+        :*)
+            p=${p#:}
+            local ans
+            ans="$(find "$HOME" \
+                -path "$HOME/Library" -prune \
+                -o -path "$HOME/.*" -prune \
+                -o -path "*/.git" -prune \
+                -o -name "*$p*" -type d -print 2>/dev/null)"
+            if [ "$ans" = "" ]; then
+                printf "%s\n" "not found: " 2>/dev/null
+                return 1
+            fi
+            ___x_cmd_cd_choose "$ans"
+            ;;
+        /*)    ___x_cmd_cd_choose "$(___x_cmd_cd_iter / "${p#/}")" ;;
+        */*)   ___x_cmd_cd_choose "$(___x_cmd_cd_iter . "${p}")"   ;;
+        *)
+            ___X_CMD_CD_HISTORY="$(printf "%s" "$___X_CMD_CD_HISTORY" | awk "$___X_CMD_AWK_CODE")"
+            ___x_cmd_cd_choose "$(printf "%s" "$___X_CMD_CD_HISTORY" | grep "${p#-}")"
+            ;;
+    esac
+}
+# EndSection
 
 # Section: choose
 
@@ -50,7 +121,6 @@ A
     fi
 }
 # EndSection
-
 
 # Section: cd back
 ___x_cmd_cd_back(){
@@ -189,76 +259,6 @@ END {
 }
 ___x_cmd_cd_load_history
 
-# EndSection
-
-# Section: main
-___x_cmd_cd(){
-    local p="$1"
-
-    if [ -d "$p" ]; then
-        ___x_cmd_cd_origin "$p"
-        return
-    fi
-
-    case "$p" in
-        "")      ___x_cmd_cd_origin              ;;
-        ...)     ___x_cmd_cd_origin ../..        ;;
-        ....)    ___x_cmd_cd_origin ../../../    ;;
-        ../*)    ___x_cmd_cd_back "${p#../}"     ;;
-        ./*)     ___x_cmd_cd_choose "$(find . -name "*${p#./}*" -type d 2>/dev/null)" ;;
-
-        # Self defined documents
-        -%)
-            ___X_CMD_CD_HISTORY="$(printf "%s" "$___X_CMD_CD_HISTORY" | awk "$___X_CMD_AWK_CODE")"
-            printf "%s\n" "$___X_CMD_CD_HISTORY"
-            ;;
-        -/)
-            # very less used
-            ___X_CMD_CD_HISTORY=
-            ;;
-        -)
-            # cd to most recent
-            ___x_cmd_cd_origin -
-            ;;
-        --)
-            ___X_CMD_CD_HISTORY="$(printf "%s" "$___X_CMD_CD_HISTORY" | awk "$___X_CMD_AWK_CODE")"
-            local target="${___X_CMD_CD_HISTORY#*
-*
-}"
-            [ "$target" = "$___X_CMD_CD_HISTORY" ] && printf "%s\n" "cd: no such directory: " >&2 && return
-            target="${target%%
-*}"
-            ___x_cmd_cd_origin "$target"
-            ;;
-        -*)
-            ___X_CMD_CD_HISTORY="$(printf "%s" "$___X_CMD_CD_HISTORY" | awk "$___X_CMD_AWK_CODE")"
-            ___x_cmd_cd_origin "$(awk "FNR <= 1" <<A
-$(printf "%s" "$___X_CMD_CD_HISTORY" | grep "${p#-}")
-A
-)"
-            ;;
-        :*)
-            p=${p#:}
-            local ans
-            ans="$(find "$HOME" \
-                -path "$HOME/Library" -prune \
-                -o -path "$HOME/.*" -prune \
-                -o -path "*/.git" -prune \
-                -o -name "*$p*" -type d -print 2>/dev/null)"
-            if [ "$ans" = "" ]; then
-                printf "%s\n" "not found: " 2>/dev/null
-                return 1
-            fi
-            ___x_cmd_cd_choose "$ans"
-            ;;
-        /*)    ___x_cmd_cd_choose "$(___x_cmd_cd_iter / "${p#/}")" ;;
-        */*)   ___x_cmd_cd_choose "$(___x_cmd_cd_iter . "${p}")"   ;;
-        *)
-            ___X_CMD_CD_HISTORY="$(printf "%s" "$___X_CMD_CD_HISTORY" | awk "$___X_CMD_AWK_CODE")"
-            ___x_cmd_cd_choose "$(printf "%s" "$___X_CMD_CD_HISTORY" | grep "${p#-}")"
-            ;;
-    esac
-}
 # EndSection
 
 # Section: advise
